### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Danny616** [amirzaidi/GoogleIcons#13]
I'm really not the greatest fan of OnePlus's system icons but I love their launcher, is there any way that your icon pack can be compatible with OP's launcher?

**Comment by ejdzipi** [comment]
@amirzaidi can you please make this awesome icon pack compatible with Oneplus Launcher?
Thanks

**Comment by kftrainer** [comment]
I would love that as well since I cannot access those icons from the one
plus launcher
best regards
Capt kirk
