### ISSUE TITLE
2 icons missing since Android 9 Pie on Samsung Galaxy S8

### ISSUE THREAD

**Issue by Treveo** [amirzaidi/GoogleIcons#17]
Since I updated my Samsung Galaxy S8 to Android 9, 2 icons are missing:

- Phone
- File Manager

They are converted to Samsung's ones.

**Comment by Treveo** [comment]
@amirzaidi: Could you let me know if you are planning to fix this issue?

**Comment by amirzaidi** [comment]
Some day... I'll have time soon when DNGP is ready for public release

**Comment by fawaz666** [comment]
Uderyu

**Comment by Treveo** [comment]
@amirzaidi: anytime soon? ;-)

**Comment by Treveo** [comment]
@amirzaidi: I guess you are still busy with DNGP?

**Comment by amirzaidi** [comment]
I just forgot, been working on Shade. Could you give me the full component names of the two apps that have missing icons? You can use Shade debug builds from my Telegram channel (@appforks) to easily find the component names, including activity name

**Comment by Treveo** [comment]
Phone
APK: /system/priv-app/TelephonyUI/TelephonyUI.apk
Package name: com.samsung.android.app.telephonyui

File Manager
APK: /system/priv-app/SecMyFiles2018/SecMyFiles2018.apk
Package name: com.sec.android.app.myfiles

**Comment by amirzaidi** [comment]
That's not the component name, I need the activity name or component name too.

**Comment by Treveo** [comment]
This is what Shade gives:

com.samsung.android.dialer/com.samsung.android.dialer.DialtactsActivity

And

com.sec.android.app.myfiles/com.sec.android.app.myfiles.external.ui.MainActivity

**Comment by Treveo** [comment]
Is this the info you need, @amirzaidi?

**Comment by Treveo** [comment]
@amirzaidi :-)?

**Comment by amirzaidi** [comment]
Adding them in v10

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/GoogleIcons/commit/8e9e7ee735da0ff7b299b05fd94766bd81782561
