### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by Poussinou** [amirzaidi/GoogleIcons#19]
Hi,

What's the license of this project? And also, what are the license of the icons?

If at least the source code is open-source, we could add this app to F-Droid !

**Comment by amirzaidi** [comment]
> What's the license of this project?

I'd love to throw GPL or any other open source license on it...

> And also, what are the license of the icons?

This is the problem. Almost all of the icons are ripped from Google apps, so I have no idea what licenses I can add. I'm surprised Google hasn't taken down the app from the Play Store yet.

**Comment by Poussinou** [comment]
I think you can put GNU GPL v3 license on the source code of the app, but you should add a word in the readme and/or directly inin the source code that the icons aren't yours and aren't FLOSS.

I think we could then add this icon pack with a flag stating that it contains non free (as in freedom) assets, and I think it should be enough

**Comment by Poussinou** [comment]
@amirzaidi Any news about this?
